[build]
  command = "bun run build:static"
  publish = "out"

[build.environment]
  NODE_VERSION = "20"

[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
